"""
BLOG INDEX BUILDER
------------------
Scans every  blog/<slug>/index.html  file, reads its <title> and
<meta name="description">, and regenerates  blog/index.html  as a
card grid, newest post first.

Post dates come from  blog/posts.json  (created automatically):
the first time a post is seen it is stamped with today's date.
To change a post's date or order, edit blog/posts.json by hand.

Run manually:   python scripts/build_blog_index.py
On GitHub:      runs automatically on every push (see
                .github/workflows/build-blog.yml)
"""
import json
import re
import sys
from datetime import date
from pathlib import Path

SITE_DIR = Path(__file__).resolve().parent.parent
BLOG_DIR = SITE_DIR / "blog"
MANIFEST = BLOG_DIR / "posts.json"
OUTPUT = BLOG_DIR / "index.html"


def extract(pattern, html, default=""):
    m = re.search(pattern, html, re.IGNORECASE | re.DOTALL)
    return re.sub(r"\s+", " ", m.group(1)).strip() if m else default


def scan_posts():
    manifest = {}
    if MANIFEST.exists():
        manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))

    posts = []
    # sort case-insensitively so Windows (local) and Linux (GitHub Action)
    # produce identical output and don't ping-pong commits
    for post_file in sorted(BLOG_DIR.glob("*/index.html"), key=lambda p: str(p).lower()):
        slug = post_file.parent.name
        html = post_file.read_text(encoding="utf-8", errors="ignore")
        title = extract(r"<title[^>]*>(.*?)</title>", html, slug.replace("-", " ").title())
        desc = extract(
            r'<meta\s+name=["\']description["\']\s+content=["\'](.*?)["\']', html
        ) or extract(
            r'<meta\s+content=["\'](.*?)["\']\s+name=["\']description["\']', html
        )
        if slug not in manifest:
            manifest[slug] = {"date": date.today().isoformat()}
        posts.append({
            "slug": slug,
            "title": title,
            "desc": desc,
            "date": manifest[slug]["date"],
        })

    # drop manifest entries whose folder was deleted
    manifest = {p["slug"]: manifest[p["slug"]] for p in posts}
    MANIFEST.write_text(json.dumps(manifest, indent=2, sort_keys=True), encoding="utf-8")

    posts.sort(key=lambda p: (p["date"], p["slug"]), reverse=True)
    return posts


def nice_date(iso):
    d = date.fromisoformat(iso)
    return d.strftime("%d %b %Y")


def build(posts):
    if posts:
        cards = "\n".join(
            f'''    <a class="post-card" href="{p["slug"]}/index.html">
      <div class="date">{nice_date(p["date"])}</div>
      <h3>{p["title"]}</h3>
      <p>{p["desc"]}</p>
      <div class="read">READ ARTICLE →</div>
    </a>''' for p in posts)
        body = f'  <div class="blog-grid">\n{cards}\n  </div>'
    else:
        body = '  <p class="blog-empty">No articles published yet — check back soon.</p>'

    OUTPUT.write_text(f'''<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Blog | SSH Network — Chartered Accountants</title>
<meta name="description" content="Articles and insights from SSH Network — audit, tax, AI and automation for finance professionals.">
<link rel="icon" href="../assets/images/logo.png">
<link rel="stylesheet" href="../assets/css/style.css">
</head>
<!-- AUTO-GENERATED by scripts/build_blog_index.py — DO NOT EDIT BY HAND.
     To add a post: create blog/<slug>/index.html and push. -->
<body data-root="../">

<div id="site-header"></div>

<div class="page-hero">
  <h1>Blog &amp; Insights</h1>
  <p>Articles on audit, tax, AI and automation for finance professionals.</p>
</div>

<section><div class="wrap">
{body}
</div></section>

<footer id="site-footer"></footer>

<script src="../content/site.js"></script>
<script src="../assets/js/render.js"></script>
<script>renderHeader("Blog"); renderFooter();</script>
<script src="../assets/js/effects.js"></script>
</body>
</html>
''', encoding="utf-8")


if __name__ == "__main__":
    posts = scan_posts()
    build(posts)
    print(f"blog/index.html regenerated with {len(posts)} post(s).")
    sys.exit(0)
